version: "3.3"
services:  
    mysql:
        container_name: sql
        image: mysql
        volumes:
            - ./db:/var/lib/mysql
        ports:
            - "3306:3306"
        hostname: R8WA
        restart: always
        command: --lower_case_table_names=1
        environment:
            MYSQL_DATABASE: 'database'
            MYSQL_USER: 'sloth'
            MYSQL_PASSWORD: 'sloth'
            MYSQL_ROOT_PASSWORD: 'sloth'
            MYSQL_ROOT_PASSWORD: 'sloth'
    dash:
        build:
            context: .
            dockerfile: DockerfileDash
        container_name: dash_server
        command: python app.py
        restart: always
        volumes:
            - .:/code
        ports:
            - "80:8080"
        links:
            - "mysql:mysql"
    jupyter:
        container_name: notebook
        build: 
            context: .
            dockerfile: DockerfileJupyter
        volumes:
            - .:/home/jovyan/aaa
        depends_on: 
            - mysql
        ports:
            - "8888:8888"